"""
generate_data.py

Generates synthetic hospital source-system data.

This project does NOT use real patient information.
All records generated by this script are synthetic and
created only for educational/data-engineering purposes.
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

from config import RAW_DIR, SOURCE_FILES


# ============================================================
# REPRODUCIBILITY
# ============================================================

RNG = np.random.default_rng(42)


# ============================================================
# DATASET CONFIGURATION
# ============================================================

N_PATIENTS = 200
N_APPOINTMENTS = 1200

START_DATE = pd.Timestamp("2026-08-01")


# ============================================================
# PATIENT DATA
# ============================================================

FIRST_NAMES = [
    "Ravi",
    "Sita",
    "Kiran",
    "Lakshmi",
    "Suresh",
    "Anitha",
    "Rahul",
    "Priya",
    "Venkat",
    "Divya",
    "Srinivas",
    "Kavya",
    "Arjun",
    "Meena",
    "Mahesh",
    "Swathi",
    "Naveen",
    "Bhavya",
]

LAST_NAMES = [
    "Kumar",
    "Reddy",
    "Rao",
    "Naidu",
    "Sharma",
    "Chowdary",
    "Varma",
    "Prasad",
    "Goud",
    "Shetty",
]

CITIES = [
    "Hyderabad",
    "Vijayawada",
    "Guntur",
    "Warangal",
    "Nellore",
    "Kurnool",
    "Nizamabad",
]

BLOOD_GROUPS = [
    "A+",
    "B+",
    "O+",
    "AB+",
    "A-",
    "B-",
    "O-",
]

CHRONIC_CONDITIONS = [
    "None",
    "Diabetes",
    "Hypertension",
    "Heart Disease",
    "Asthma",
    "Kidney Disease",
]


# ============================================================
# HOSPITAL STRUCTURE
# ============================================================

DEPARTMENTS = {
    "Cardiology": [
        "D01",
        "D02",
    ],
    "General Medicine": [
        "D03",
        "D04",
        "D05",
    ],
    "Orthopedics": [
        "D06",
        "D07",
    ],
    "Pediatrics": [
        "D08",
    ],
    "Neurology": [
        "D09",
    ],
    "Pulmonology": [
        "D10",
    ],
}


# ============================================================
# PATIENT GENERATOR
# ============================================================

def generate_patients() -> pd.DataFrame:
    """
    Generate synthetic patient-registration data.

    The raw data intentionally contains data-quality issues
    that will later be handled by the Transform stage.
    """

    patient_ids = [
        f"P{i:04d}"
        for i in range(1, N_PATIENTS + 1)
    ]

    # --------------------------------------------------------
    # Generate ages
    # --------------------------------------------------------

    ages = RNG.integers(
        low=2,
        high=90,
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate dates of birth
    # --------------------------------------------------------

    date_of_birth = []

    for age in ages:

        random_days = int(
            RNG.integers(
                low=0,
                high=365,
            )
        )

        dob = (
            START_DATE
            - pd.DateOffset(
                years=int(age)
            )
            - pd.Timedelta(
                days=random_days
            )
        )

        date_of_birth.append(
            dob.date()
        )

    # --------------------------------------------------------
    # Generate names
    # --------------------------------------------------------

    names = []

    for _ in patient_ids:

        first_name = RNG.choice(
            FIRST_NAMES
        )

        last_name = RNG.choice(
            LAST_NAMES
        )

        name = f"{first_name} {last_name}"

        # 20% contain extra spaces
        if RNG.random() < 0.20:
            name = f" {name} "

        names.append(name)

    # --------------------------------------------------------
    # Generate inconsistent gender values
    # --------------------------------------------------------

    genders = RNG.choice(
        [
            "M",
            "Male",
            "male",
            "F",
            "Female",
            "female",
        ],
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate cities
    # --------------------------------------------------------

    cities = RNG.choice(
        CITIES,
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate blood groups
    # --------------------------------------------------------

    blood_groups = RNG.choice(
        BLOOD_GROUPS,
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate chronic conditions
    # --------------------------------------------------------

    chronic_conditions = []

    for age in ages:

        if age < 30:

            condition = RNG.choice(
                [
                    "None",
                    "Asthma",
                ],
                p=[
                    0.92,
                    0.08,
                ],
            )

        else:

            condition = RNG.choice(
                CHRONIC_CONDITIONS,
                p=[
                    0.45,
                    0.15,
                    0.15,
                    0.10,
                    0.08,
                    0.07,
                ],
            )

        chronic_conditions.append(
            condition
        )

    # --------------------------------------------------------
    # Generate registration dates
    # --------------------------------------------------------

    registration_dates = []

    for _ in patient_ids:

        days_before_registration = int(
            RNG.integers(
                low=0,
                high=700,
            )
        )

        registration_date = (
            START_DATE
            - pd.Timedelta(
                days=days_before_registration
            )
        )

        registration_dates.append(
            registration_date.date()
        )

    # --------------------------------------------------------
    # Build DataFrame
    # --------------------------------------------------------

    patients = pd.DataFrame(
        {
            "patient_id": patient_ids,
            "name": names,
            "gender": genders,
            "date_of_birth": date_of_birth,
            "city": cities,
            "blood_group": blood_groups,
            "chronic_condition": chronic_conditions,
            "registration_date": registration_dates,
        }
    )

    # ========================================================
    # INTENTIONAL DATA-QUALITY PROBLEMS
    # ========================================================

    # --------------------------------------------------------
    # Missing blood groups
    # --------------------------------------------------------

    missing_blood_group_indices = RNG.choice(
        N_PATIENTS,
        size=10,
        replace=False,
    )

    patients.loc[
        missing_blood_group_indices,
        "blood_group",
    ] = np.nan

    # --------------------------------------------------------
    # Missing cities
    # --------------------------------------------------------

    missing_city_indices = RNG.choice(
        N_PATIENTS,
        size=8,
        replace=False,
    )

    patients.loc[
        missing_city_indices,
        "city",
    ] = np.nan

    # --------------------------------------------------------
    # Represent "None" as missing in raw source
    # --------------------------------------------------------

    patients.loc[
        patients["chronic_condition"] == "None",
        "chronic_condition",
    ] = np.nan

    # --------------------------------------------------------
    # Duplicate patient registrations
    # --------------------------------------------------------

    duplicate_rows = patients.sample(
        n=6,
        random_state=42,
    )

    patients = pd.concat(
        [
            patients,
            duplicate_rows,
        ],
        ignore_index=True,
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    os.makedirs(
        RAW_DIR,
        exist_ok=True,
    )

    output_path = SOURCE_FILES["patients"]

    patients.to_csv(
        output_path,
        index=False,
    )

    return patients


# ============================================================
# APPOINTMENT GENERATOR
# ============================================================

def generate_appointments(
    patients: pd.DataFrame,
) -> pd.DataFrame:
    """
    Generate synthetic appointment-scheduling data.

    The data contains:
    - completed appointments
    - no-shows
    - cancellations
    - realistic waiting times
    - intentionally invalid records
    - unknown patient IDs
    """

    # --------------------------------------------------------
    # Use unique patient IDs.
    #
    # The patient source contains duplicate registrations,
    # but the appointment system should normally reference
    # logical patients.
    # --------------------------------------------------------

    valid_patient_ids = (
        patients["patient_id"]
        .drop_duplicates()
        .tolist()
    )

    rows = []

    # --------------------------------------------------------
    # Generate appointments
    # --------------------------------------------------------

    for i in range(
        1,
        N_APPOINTMENTS + 1,
    ):

        # Pick department
        department = RNG.choice(
            list(DEPARTMENTS.keys())
        )

        # Pick doctor from department
        doctor_id = RNG.choice(
            DEPARTMENTS[department]
        )

        # Pick patient
        patient_id = RNG.choice(
            valid_patient_ids
        )

        # Random appointment day
        day_offset = int(
            RNG.integers(
                low=0,
                high=45,
            )
        )

        appointment_day = (
            START_DATE
            + pd.Timedelta(
                days=day_offset
            )
        )

        # ----------------------------------------------------
        # Hospital appointment hours
        # ----------------------------------------------------

        hour = int(
            RNG.choice(
                [
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                ],
                p=[
                    0.12,
                    0.20,
                    0.20,
                    0.15,
                    0.08,
                    0.10,
                    0.08,
                    0.07,
                ],
            )
        )

        minute = int(
            RNG.choice(
                [
                    0,
                    15,
                    30,
                    45,
                ]
            )
        )

        scheduled_time = (
            appointment_day
            + pd.Timedelta(
                hours=hour,
                minutes=minute,
            )
        )

        # ----------------------------------------------------
        # Appointment status
        # ----------------------------------------------------

        status = RNG.choice(
            [
                "Completed",
                "No-Show",
                "Cancelled",
            ],
            p=[
                0.82,
                0.12,
                0.06,
            ],
        )

        checkin_time = pd.NaT
        consultation_start_time = pd.NaT

        # ----------------------------------------------------
        # Completed appointment
        # ----------------------------------------------------

        if status == "Completed":

            # Patient checks in slightly before or after
            # the scheduled time.

            checkin_offset = int(
                RNG.integers(
                    low=-15,
                    high=10,
                )
            )

            checkin_time = (
                scheduled_time
                + pd.Timedelta(
                    minutes=checkin_offset
                )
            )

            # Base consultation waiting time
            base_wait_by_department = {
                "Cardiology": 35,
                "General Medicine": 45,
                "Orthopedics": 30,
                "Pediatrics": 20,
                "Neurology": 25,
                "Pulmonology": 25,
            }

            base_wait = (
                base_wait_by_department[
                    department
                ]
            )

            # Morning rush
            peak_wait = (
                20
                if hour in (10, 11)
                else 0
            )

            waiting_time = max(
                2,
                int(
                    RNG.normal(
                        base_wait + peak_wait,
                        12,
                    )
                ),
            )

            consultation_start_time = (
                checkin_time
                + pd.Timedelta(
                    minutes=waiting_time
                )
            )

        rows.append(
            [
                f"A{i:05d}",
                patient_id,
                doctor_id,
                department,
                scheduled_time,
                checkin_time,
                consultation_start_time,
                status,
            ]
        )

    # --------------------------------------------------------
    # Create DataFrame
    # --------------------------------------------------------

    appointments = pd.DataFrame(
        rows,
        columns=[
            "appointment_id",
            "patient_id",
            "doctor_id",
            "department",
            "scheduled_time",
            "checkin_time",
            "consultation_start_time",
            "status",
        ],
    )

    # ========================================================
    # INTENTIONAL DATA-QUALITY PROBLEMS
    # ========================================================

    # --------------------------------------------------------
    # 1. Unknown patient IDs
    # --------------------------------------------------------
    #
    # These patients don't exist in patients.csv.
    #
    # This will later test referential integrity.
    # --------------------------------------------------------

    unknown_patient_indices = RNG.choice(
        len(appointments),
        size=5,
        replace=False,
    )

    appointments.loc[
        unknown_patient_indices,
        "patient_id",
    ] = "P9999"

    # --------------------------------------------------------
    # 2. Invalid timestamps
    # --------------------------------------------------------
    #
    # consultation_start_time occurs before check-in.
    #
    # This creates a negative waiting time.
    # --------------------------------------------------------

    completed_indices = appointments.index[
        appointments["status"] == "Completed"
    ]

    invalid_time_indices = RNG.choice(
        completed_indices,
        size=8,
        replace=False,
    )

    appointments.loc[
        invalid_time_indices,
        "consultation_start_time",
    ] = (
        appointments.loc[
            invalid_time_indices,
            "checkin_time",
        ]
        - pd.Timedelta(
            minutes=30
        )
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    output_path = SOURCE_FILES[
        "appointments"
    ]

    appointments.to_csv(
        output_path,
        index=False,
    )

    return appointments
# ============================================================
# LABORATORY REPORT GENERATOR
# ============================================================

def generate_lab_reports(
    patients: pd.DataFrame,
) -> list[dict]:
    """
    Generate synthetic laboratory reports in JSON format.

    Each patient can have multiple laboratory tests.

    Intentional raw-data issues:
    - missing results
    - numeric values stored as strings
    - abnormal results associated with chronic conditions
    """

    # --------------------------------------------------------
    # Base distributions for normal patients
    #
    # (mean, standard deviation, unit)
    # --------------------------------------------------------

    normal_ranges = {
        "Hemoglobin": (
            14.0,
            1.5,
            "g/dL",
        ),

        "Fasting Blood Sugar": (
            90.0,
            8.0,
            "mg/dL",
        ),

        "Total Cholesterol": (
            175.0,
            20.0,
            "mg/dL",
        ),

        "Creatinine": (
            0.95,
            0.15,
            "mg/dL",
        ),

        "WBC Count": (
            7.5,
            1.5,
            "10^3/uL",
        ),
    }

    # --------------------------------------------------------
    # Chronic-condition shifts
    #
    # This makes the synthetic dataset more realistic.
    # --------------------------------------------------------

    condition_shifts = {
        "Diabetes": {
            "Fasting Blood Sugar": 60,
        },

        "Heart Disease": {
            "Total Cholesterol": 60,
        },

        "Hypertension": {
            "Total Cholesterol": 35,
        },

        "Kidney Disease": {
            "Creatinine": 1.2,
        },
    }

    reports = []

    report_number = 1

    # --------------------------------------------------------
    # Generate tests for each patient
    # --------------------------------------------------------

    for _, patient in patients.drop_duplicates(
        "patient_id"
    ).iterrows():

        patient_id = patient["patient_id"]

        chronic_condition = (
            patient["chronic_condition"]
            if pd.notna(
                patient["chronic_condition"]
            )
            else "None"
        )

        for test_name, (
            mean,
            std,
            unit,
        ) in normal_ranges.items():

            # ------------------------------------------------
            # Not every patient gets every test.
            #
            # This creates realistic sparsity.
            # ------------------------------------------------

            if RNG.random() < 0.30:
                continue

            # ------------------------------------------------
            # Apply chronic-condition shift
            # ------------------------------------------------

            shift = (
                condition_shifts
                .get(
                    chronic_condition,
                    {},
                )
                .get(
                    test_name,
                    0,
                )
            )

            value = RNG.normal(
                mean + shift,
                std,
            )

            value = round(
                float(value),
                2,
            )

            # ------------------------------------------------
            # Occasionally create a missing lab result
            # ------------------------------------------------

            if RNG.random() < 0.03:

                value = None

            # ------------------------------------------------
            # Occasionally store numeric value as string
            # ------------------------------------------------

            elif RNG.random() < 0.15:

                value = str(value)

            # ------------------------------------------------
            # Random report date
            # ------------------------------------------------

            report_date = (
                START_DATE
                + pd.Timedelta(
                    days=int(
                        RNG.integers(
                            low=0,
                            high=45,
                        )
                    )
                )
            )

            reports.append(
                {
                    "report_id": (
                        f"L{report_number:05d}"
                    ),

                    "patient_id": patient_id,

                    "test_name": test_name,

                    "result_value": value,

                    "unit": unit,

                    "report_date": str(
                        report_date.date()
                    ),
                }
            )

            report_number += 1

    # --------------------------------------------------------
    # JSON output structure
    # --------------------------------------------------------

    lab_data = {
        "source": "hospital_lab_system",
        "generated_at": str(
            pd.Timestamp.now()
        ),
        "reports": reports,
    }

    # --------------------------------------------------------
    # Save JSON
    # --------------------------------------------------------

    os.makedirs(
        RAW_DIR,
        exist_ok=True,
    )

    output_path = SOURCE_FILES[
        "lab_reports"
    ]

    import json

    with open(
        output_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            lab_data,
            file,
            indent=2,
        )

    return reports

# ============================================================
# MAIN
# ============================================================

def main() -> None:
    """
    Generate all currently implemented synthetic
    hospital source datasets.
    """

    print("=" * 60)
    print("HOSPITAL SOURCE DATA GENERATION")
    print("=" * 60)

    # --------------------------------------------------------
    # Generate patients
    # --------------------------------------------------------

    patients = generate_patients()

    print()
    print("PATIENT REGISTRATION")
    print("-" * 60)

    print(
        f"Rows               : {len(patients)}"
    )

    print(
        f"Unique patients    : "
        f"{patients['patient_id'].nunique()}"
    )

    print(
        f"Duplicate rows     : "
        f"{patients['patient_id'].duplicated().sum()}"
    )

    # --------------------------------------------------------
    # Generate appointments
    # --------------------------------------------------------

    appointments = generate_appointments(
        patients
    )
        # --------------------------------------------------------
    # Generate laboratory reports
    # --------------------------------------------------------

    lab_reports = generate_lab_reports(
        patients
    )

    print()
    print("LABORATORY SYSTEM")
    print("-" * 60)

    print(
        f"Lab reports        : {len(lab_reports)}"
    )

    print(
        f"Missing results    : "
        f"{sum(
            report['result_value'] is None
            for report in lab_reports
        )}"
    )

    print(
        f"String results     : "
        f"{sum(
            isinstance(
                report['result_value'],
                str,
            )
            for report in lab_reports
        )}"
    )

    print(
        f"Saved to           : "
        f"{SOURCE_FILES['lab_reports']}"
    )
    print()
    print("APPOINTMENT SYSTEM")
    print("-" * 60)

    print(
        f"Appointments       : {len(appointments)}"
    )

    print(
        f"Completed          : "
        f"{(appointments['status'] == 'Completed').sum()}"
    )

    print(
        f"No-Show            : "
        f"{(appointments['status'] == 'No-Show').sum()}"
    )

    print(
        f"Cancelled          : "
        f"{(appointments['status'] == 'Cancelled').sum()}"
    )

    print(
        f"Unknown patients   : "
        f"{(~appointments['patient_id'].isin(
            patients['patient_id']
        )).sum()}"
    )

    # --------------------------------------------------------
    # Calculate intentionally invalid waiting records
    # --------------------------------------------------------

    completed = appointments[
        appointments["status"] == "Completed"
    ].copy()

    waiting_minutes = (
        completed["consultation_start_time"]
        - completed["checkin_time"]
    ).dt.total_seconds() / 60

    print(
        f"Negative waits     : "
        f"{(waiting_minutes < 0).sum()}"
    )

    print()
    print("Generated files:")
    print(
        f"  patients      → "
        f"{SOURCE_FILES['patients']}"
    )
    print(
        f"  appointments  → "
        f"{SOURCE_FILES['appointments']}"
    )


if __name__ == "__main__":
    main()