"""
generate_data.py

Generates synthetic hospital source-system data.

This project does NOT use real patient information.
All records generated by this script are synthetic and
created only for educational/data-engineering purposes.
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

from config import RAW_DIR, SOURCE_FILES


# ============================================================
# REPRODUCIBILITY
# ============================================================

RNG = np.random.default_rng(42)


# ============================================================
# DATASET CONFIGURATION
# ============================================================

N_PATIENTS = 200

START_DATE = pd.Timestamp("2026-08-01")

FIRST_NAMES = [
    "Ravi",
    "Sita",
    "Kiran",
    "Lakshmi",
    "Suresh",
    "Anitha",
    "Rahul",
    "Priya",
    "Venkat",
    "Divya",
    "Srinivas",
    "Kavya",
    "Arjun",
    "Meena",
    "Mahesh",
    "Swathi",
    "Naveen",
    "Bhavya",
]

LAST_NAMES = [
    "Kumar",
    "Reddy",
    "Rao",
    "Naidu",
    "Sharma",
    "Chowdary",
    "Varma",
    "Prasad",
    "Goud",
    "Shetty",
]

CITIES = [
    "Hyderabad",
    "Vijayawada",
    "Guntur",
    "Warangal",
    "Nellore",
    "Kurnool",
    "Nizamabad",
]

BLOOD_GROUPS = [
    "A+",
    "B+",
    "O+",
    "AB+",
    "A-",
    "B-",
    "O-",
]

CHRONIC_CONDITIONS = [
    "None",
    "Diabetes",
    "Hypertension",
    "Heart Disease",
    "Asthma",
    "Kidney Disease",
]


# ============================================================
# PATIENT GENERATOR
# ============================================================

def generate_patients() -> pd.DataFrame:
    """
    Generate synthetic patient-registration data.

    The raw data intentionally contains data-quality issues
    that will later be handled by the Transform stage.
    """

    patient_ids = [
        f"P{i:04d}"
        for i in range(1, N_PATIENTS + 1)
    ]

    # --------------------------------------------------------
    # Generate realistic ages
    # --------------------------------------------------------

    ages = RNG.integers(
        low=2,
        high=90,
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate date of birth from age
    # --------------------------------------------------------

    date_of_birth = []

    for age in ages:

        random_days = int(
            RNG.integers(
                low=0,
                high=365,
            )
        )

        dob = (
            START_DATE
            - pd.DateOffset(years=int(age))
            - pd.Timedelta(days=random_days)
        )

        date_of_birth.append(
            dob.date()
        )

    # --------------------------------------------------------
    # Generate names
    #
    # We intentionally add spaces around some names.
    # This becomes a transformation problem later.
    # --------------------------------------------------------

    names = []

    for _ in patient_ids:

        first_name = RNG.choice(FIRST_NAMES)
        last_name = RNG.choice(LAST_NAMES)

        name = f"{first_name} {last_name}"

        # 20% of records contain extra spaces
        if RNG.random() < 0.20:
            name = f" {name} "

        names.append(name)

    # --------------------------------------------------------
    # Generate inconsistent gender values
    #
    # Example:
    # M, Male, male, F, Female, female
    # --------------------------------------------------------

    genders = RNG.choice(
        [
            "M",
            "Male",
            "male",
            "F",
            "Female",
            "female",
        ],
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate cities
    # --------------------------------------------------------

    cities = RNG.choice(
        CITIES,
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate blood groups
    # --------------------------------------------------------

    blood_groups = RNG.choice(
        BLOOD_GROUPS,
        size=N_PATIENTS,
    )

    # --------------------------------------------------------
    # Generate chronic conditions
    #
    # Younger patients mostly receive "None".
    # Older patients have a higher chance of chronic disease.
    # --------------------------------------------------------

    chronic_conditions = []

    for age in ages:

        if age < 30:

            condition = RNG.choice(
                [
                    "None",
                    "Asthma",
                ],
                p=[
                    0.92,
                    0.08,
                ],
            )

        else:

            condition = RNG.choice(
                CHRONIC_CONDITIONS,
                p=[
                    0.45,  # None
                    0.15,  # Diabetes
                    0.15,  # Hypertension
                    0.10,  # Heart Disease
                    0.08,  # Asthma
                    0.07,  # Kidney Disease
                ],
            )

        chronic_conditions.append(condition)

    # --------------------------------------------------------
    # Registration dates
    #
    # Each patient registered some time before START_DATE.
    # --------------------------------------------------------

    registration_dates = []

    for _ in patient_ids:

        days_before_registration = int(
            RNG.integers(
                low=0,
                high=700,
            )
        )

        registration_date = (
            START_DATE
            - pd.Timedelta(
                days=days_before_registration
            )
        )

        registration_dates.append(
            registration_date.date()
        )

    # --------------------------------------------------------
    # Create DataFrame
    # --------------------------------------------------------

    patients = pd.DataFrame(
        {
            "patient_id": patient_ids,
            "name": names,
            "gender": genders,
            "date_of_birth": date_of_birth,
            "city": cities,
            "blood_group": blood_groups,
            "chronic_condition": chronic_conditions,
            "registration_date": registration_dates,
        }
    )

    # ========================================================
    # INTENTIONAL DATA-QUALITY PROBLEMS
    # ========================================================

    # --------------------------------------------------------
    # 1. Missing blood groups
    # --------------------------------------------------------

    missing_blood_group_indices = RNG.choice(
        N_PATIENTS,
        size=10,
        replace=False,
    )

    patients.loc[
        missing_blood_group_indices,
        "blood_group",
    ] = np.nan

    # --------------------------------------------------------
    # 2. Missing cities
    # --------------------------------------------------------

    missing_city_indices = RNG.choice(
        N_PATIENTS,
        size=8,
        replace=False,
    )

    patients.loc[
        missing_city_indices,
        "city",
    ] = np.nan

    # --------------------------------------------------------
    # 3. Store "None" chronic condition as missing.
    #
    # This simulates a source system that leaves the field
    # blank when the patient has no chronic condition.
    # --------------------------------------------------------

    patients.loc[
        patients["chronic_condition"] == "None",
        "chronic_condition",
    ] = np.nan

    # --------------------------------------------------------
    # 4. Duplicate patient registrations
    #
    # We duplicate six existing rows.
    # The Transform phase will remove them using patient_id.
    # --------------------------------------------------------

    duplicate_rows = patients.sample(
        n=6,
        random_state=42,
    )

    patients = pd.concat(
        [
            patients,
            duplicate_rows,
        ],
        ignore_index=True,
    )

    # --------------------------------------------------------
    # Save raw data
    # --------------------------------------------------------

    os.makedirs(
        RAW_DIR,
        exist_ok=True,
    )

    output_path = SOURCE_FILES["patients"]

    patients.to_csv(
        output_path,
        index=False,
    )

    return patients


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    """
    Generate the patient-registration source dataset.
    """

    patients = generate_patients()

    print("=" * 60)
    print("PATIENT DATA GENERATION")
    print("=" * 60)

    print(
        f"Generated rows      : {len(patients)}"
    )

    print(
        f"Unique patient IDs  : {patients['patient_id'].nunique()}"
    )

    print(
        f"Duplicate rows      : "
        f"{patients['patient_id'].duplicated().sum()}"
    )

    print(
        f"Missing cities      : "
        f"{patients['city'].isna().sum()}"
    )

    print(
        f"Missing blood groups: "
        f"{patients['blood_group'].isna().sum()}"
    )

    print(
        f"Missing conditions  : "
        f"{patients['chronic_condition'].isna().sum()}"
    )

    print()
    print(
        f"Saved to: {SOURCE_FILES['patients']}"
    )

    print()
    print("First 10 raw records:")
    print(
        patients.head(10).to_string(
            index=False
        )
    )


if __name__ == "__main__":
    main()